language: r

r:
  - devel

env: 
  global:
    - CRAN: https://cran.rstudio.com

os:
  - linux

dist: trusty

r_check_args: --no-build-vignettes --no-manual

# os:
#   - osx

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap

install:
  - ./travis-tool.sh install_deps

script: ./travis-tool.sh run_tests

after_failure:
  - ./travis-tool.sh dump_logs


sudo: required

notifications:
  email:
    on_success: never
    on_failure: never

